const https = require('https');
const { generatePhantomNode } = require('./page_bot');
const express = require('express');
const fs = require('fs');
const path = require('path');
const { v4: uuidv4 } = require('uuid');
// --- SAFETY NET LIBRARIES ---
const { JSDOM } = require('jsdom');
const createDOMPurify = require('dompurify');
const window = new JSDOM('').window;
const DOMPurify = createDOMPurify(window);
const archiver = require('archiver');
const unzipper = require('unzipper');
const multer = require('multer'); // You likely already have this, if not: npm install multer
const upload = multer({ dest: 'uploads/' });
const runGarbageCollector = require('./gc.js');
const { archiveDeletion, healNode, reviveNode } = require('./utils');
const session = require('express-session');
const helmet = require('helmet');
const sanitizeHtml = require('sanitize-html');
const rateLimit = require('express-rate-limit');
const axios = require('axios');

require('dotenv').config();

const app = express();
const port = process.env.PORT || 3000;
let maintenanceMode = false;
const RSSParser = require('rss-parser');
const parser = new RSSParser();



const cheerio = require('cheerio');

app.get('/proxy-browse', async (req, res) => {
    try {
        const response = await fetch(
            'https://neocities.org/browse?sort_by=last_updated',
            {
                headers: {
                    'User-Agent': 'Mozilla/5.0'
                }
            }
        );

        const html = await response.text();
        const $ = cheerio.load(html);

        const sites = [];

        $('.site-info .username a').each((i, el) => {
            const name = $(el).text().trim().toLowerCase();
            if (name) sites.push({ name });
        });

        res.json(sites.slice(0, 30));

    } catch (err) {
        console.error(err);
        res.status(500).send('Browse scrape failed');
    }
});


// Initialize directories
if (!fs.existsSync('./nodes')) fs.mkdirSync('./nodes');

// Root node initialization
const rootPath = './nodes/root.json';
if (!fs.existsSync(rootPath)) {
    fs.writeFileSync(rootPath, JSON.stringify({
        id: "root",
        title: "THE SOURCE",
        content: "<h2>Welcome to the beginning.</h2><p>This is the root of the net.</p>",
        children: [],
        views: 0,
        isUnderConstruction: false
    }));
}

async function spawnNewsSector() {
    try {
        const feed = await parser.parseURL('https://news.ycombinator.com/rss');
        const item = feed.items[0]; 
        if (!item) return;

        // 1. Generate unique ID based on title
        const nodeId = "news-" + Buffer.from(item.title).toString('hex').substring(0, 8);
        const htmlFilePath = path.join(__dirname, 'public_sites', `${nodeId}.html`);
        const jsonNodePath = path.join(__dirname, 'nodes', `${nodeId}.json`);

        // Skip if already exists
        if (fs.existsSync(jsonNodePath)) return;

        // 2. The "Bake" (HTML Template)
        const fullHtmlPage = `
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>${item.title}</title>
            <link rel="stylesheet" href="/style.css">
        </head>
        <body style="background-color: #008080; margin: 0; padding: 10px;">
            <div class="window-full">
                <div class="title-bar">
                    <span>Automated Archive: ${nodeId}</span>
                    <span>[X]</span>
                </div>
                <div class="content-area">
                    <h1 style="background: #000080; color: white; padding: 5px; font-family: 'Courier New', monospace;">
                        STORY RECOVERED: ${item.title}
                    </h1>
                    <p><b>ORIGIN:</b> <a href="${item.link}">${item.link}</a></p>
                    <p><b>TIMESTAMP:</b> ${item.pubDate}</p>
                    <hr>
                    <div style="font-family: 'Courier New', monospace; padding: 10px; border: 1px inset #808080; background: #f0f0f0;">
                        <p>> ACCESSING EXTERNAL DATA STREAM...</p>
                        <p>> [SUCCESS]</p>
                        <p>This sector was automatically generated by the Network Archivist. It mirrors content from the Hacker News grid.</p>
                        <br>
                        <a href="${item.link}" target="_blank" style="font-size: 18px; color: blue;">[ CLICK HERE TO VIEW FULL ARTICLE ]</a>
                    </div>
                    <hr style="margin-top: 30px;">
                    <center style="margin-top: 20px;">
                        <a href="https://eurosnet.up.railway.app" 
                        style="
                            display: inline-block;
                            padding: 5px 15px;
                            background: #c0c0c0;
                            border: 2px outset #ffffff;
                            color: #000000;
                            text-decoration: none;
                            font-family: 'Tahoma', sans-serif;
                            font-size: 11px;
                            font-weight: bold;
                            cursor: pointer;
                        "
                        onmousedown="this.style.borderStyle='inset'"
                        onmouseup="this.style.borderStyle='outset'">
                        [ Return to Node Net ]
                        </a>
                    </center>
                </div>
            </div>
        </body>
        </html>`;

        // 3. Save the Physical Files
        fs.writeFileSync(htmlFilePath, fullHtmlPage);

        const newNodeData = {
            id: nodeId,
            title: `[NEWS] ${item.title}`,
            isStatic: true,
            views: 0,
            children: [],
            parentId: 'root',
            timestamp: new Date().toISOString()
        };
        fs.writeFileSync(jsonNodePath, JSON.stringify(newNodeData, null, 2));

        // 4. Update the Parent (Root) so it appears in the list
        const parentPath = path.join(__dirname, 'nodes', 'root.json');
        if (fs.existsSync(parentPath)) {
            const parentData = JSON.parse(fs.readFileSync(parentPath, 'utf8'));
            parentData.children.push({ id: nodeId, title: `[NEWS] ${item.title}`, isStatic: true });
            fs.writeFileSync(parentPath, JSON.stringify(parentData, null, 2));
        }

        // 5. Post to the Bulletin Board (Graffiti Wall)
        const bulletinPath = path.join(__dirname, 'bulletin.json');
        let bulletin = [];
        if (fs.existsSync(bulletinPath)) {
            bulletin = JSON.parse(fs.readFileSync(bulletinPath, 'utf8'));
        }

        const systemMessage = {
            username: "ARCHIVIST_BOT",
            message: `📡 SIGNAL RECOVERED: "${item.title}" has been archived to sector /sites/${nodeId}.html`,
            date: new Date().toLocaleString()
        };

        bulletin.unshift(systemMessage);
        if (bulletin.length > 50) bulletin = bulletin.slice(0, 50);
        fs.writeFileSync(bulletinPath, JSON.stringify(bulletin, null, 2));

        console.log(`[NEWS-BOT]: Successfully archived: ${item.title}`);

    } catch (e) {
        console.error("News-Bot Error:", e);
    }
}





app.use(
  helmet({
    contentSecurityPolicy: {
      useDefaults: true, 
      directives: {
        "default-src": ["'self'"],
        // 1. Added Google Tag Manager here
        "script-src": ["'self'", "'unsafe-inline'", "https://www.googletagmanager.com"],
        "style-src": ["'self'", "'unsafe-inline'"],
        "img-src": ["*", "data:", "blob:", "https://images.weserv.nl"],
        "media-src": ["*", "data:", "blob:"],
        "frame-src": ["*"],
        // 2. Added corsproxy.io and Google Analytics here
        "connect-src": [
          "'self'", 
          "https://corsproxy.io", 
          "https://*.google-analytics.com", 
          "https://*.analytics.google.com", 
          "https://*.googletagmanager.com"
        ],
        "upgrade-insecure-requests": null,
      },
    },
  })
);


// 3. THE REST OF YOUR MIDDLEWARE
app.use(session({
    secret: 'retro-vibe-security-key',
    resave: false,
    saveUninitialized: false,
    saveUninitialized: true,
    cookie: { secure: false }
}));
app.use(express.static('public'));
app.use(express.urlencoded({ extended: true }));
app.use('/sites', express.static(path.join(__dirname, 'sites')));
app.set('view engine', 'ejs');
app.use(express.json({ limit: '5mb' }));
app.use(express.urlencoded({ limit: '5mb', extended: true }));

const sanitizeContent = (dirty) => {
    return sanitizeHtml(dirty, {
        allowedTags: [
            'address', 'article', 'aside', 'footer', 'header', 'h1', 'h2', 'h3', 'h4',
            'h5', 'h6', 'hgroup', 'main', 'nav', 'section', 'blockquote', 'dd', 'div',
            'dl', 'dt', 'figcaption', 'figure', 'hr', 'li', 'main', 'ol', 'p', 'pre',
            'ul', 'a', 'abbr', 'b', 'bdi', 'bdo', 'br', 'cite', 'code', 'data', 'dfn',
            'em', 'i', 'kbd', 'mark', 'q', 'rb', 'rp', 'rt', 'rtc', 'ruby', 's', 'samp',
            'small', 'span', 'strong', 'sub', 'sup', 'time', 'u', 'var', 'wbr', 'caption',
            'col', 'colgroup', 'table', 'tbody', 'td', 'tfoot', 'th', 'thead', 'tr',
            'img', 'marquee', 'center', 'video', 'source' // RETRO EXTRAS
        ],
        allowedAttributes: {
            'a': ['href', 'name', 'target'],
            'img': ['src', 'srcset', 'alt', 'title', 'width', 'height', 'loading'],
            'video': ['src', 'controls', 'width', 'height', 'autoplay', 'loop', 'muted'],
            'source': ['src', 'type'],
            '*': ['style', 'class', 'align'] // Allow style for the Geocities aesthetic
        },
        allowedStyles: {
            '*': {
                'color': [/^#/i, /rgb[/, /^[a-z]+$/],
                'background-color': [/^#/i, /rgb[/, /^[a-z]+$/],
                'text-align': [/^left$/, /^right$/, /^center$/, /^justify$/],
                'font-family': [/.*/],
                'font-size': [/.*/],
                'margin': [/.*/],
                'padding': [/.*/],
                'border': [/.*/]
            }
        }
    });
};

// Add the Rate Limiter at the top of your server.js
const spawnLimiter = rateLimit({
    windowMs: 15 * 60 * 1000, // 15 minutes
    max: 5, // Allow 5 spawns per 15 mins
    message: "<h1>SYSTEM BUSY</h1><p>Too many nodes spawned from your IP. Take a breather, traveler.</p>"
});

// --- PUBLIC ROUTES ---

app.get('/', (req, res) => res.redirect('/node/root'));

let cachedBTC = { usd: 0 }; // Persistent storage for the price
let lastFetch = 0;

app.get('/api/btc', async (req, res) => {
    const now = Date.now();
    const cacheDuration = 5 * 60 * 1000;

    // 1. Return cache if it's fresh (Removed the !== 0 check)
    // This stops the server from hammering the API while in "jail"
    if (now - lastFetch < cacheDuration) {
        return res.json({ bitcoin: cachedBTC });
    }

    try {
        const response = await axios.get('https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd', {
            timeout: 5000,
            headers: { 'User-Agent': 'Retro-Node-Network-Bot/1.0' }
        });
        
        if (response.data && response.data.bitcoin) {
            cachedBTC = response.data.bitcoin;
            lastFetch = now;
            res.json(response.data);
        } else {
            throw new Error("Invalid API Response");
        }
    } catch (error) {
        console.error('BTC Fetch Error:', error.message);
        // Set lastFetch to now even on failure so we don't spam the API 
        // until the next 5-minute window
        lastFetch = now; 
        res.json({ bitcoin: cachedBTC });
    }
});

app.get('/node/:id', (req, res) => {
    // 1. CLEAN & SYNC PATHING
    const nodeId = req.params.id.trim();
    const nodesDir = path.join(__dirname, 'nodes');
    const sitesDir = path.join(__dirname, 'sites'); // Ensure this matches your static folder
    const filePath = path.join(nodesDir, `${nodeId}.json`);
    
    // 2. EXISTENCE CHECK
    if (!fs.existsSync(filePath)) {
        console.warn(`[!] Access Denied: Node "${nodeId}" not found on disk.`);
        return res.redirect('/'); 
    }
    
    try {
        // 3. LOAD AND SYNC NODE DATA
        const fileContent = fs.readFileSync(filePath, 'utf8');
        let node = JSON.parse(fileContent);

        // Update ID if mismatched
        if (node.id !== nodeId) node.id = nodeId;

        // 3.5 STATIC BAKE REDIRECT
        // If the bot marked this as static, we MUST check if the HTML file exists.
        // If it does, we send the user to the physical site instead of rendering here.
        if (node.isStatic) {
            const staticHtmlPath = path.join(sitesDir, `${nodeId}.html`);
            if (fs.existsSync(staticHtmlPath)) {
                return res.redirect(`/sites/${nodeId}.html`);
            } else {
                console.error(`[!] Static mismatch: JSON exists for ${nodeId} but HTML is missing in /sites.`);
                // Fallback: render it dynamically anyway so they don't get a 404
            }
        }

        // Update view count
        node.views = (node.views || 0) + 1;
        fs.writeFileSync(filePath, JSON.stringify(node, null, 2));

        // 4. BROADCAST SYSTEM
        let broadcast = { message: "" };
        const broadcastPath = path.join(__dirname, 'broadcast.json');
        if (fs.existsSync(broadcastPath)) {
            try {
                broadcast = JSON.parse(fs.readFileSync(broadcastPath, 'utf8'));
            } catch (e) {}
        }

        // 5. MAINTENANCE STATUS
        const maintenanceStatus = typeof maintenanceMode !== 'undefined' ? maintenanceMode : false;

        // 6. SIDEBAR: RECENT NODES
        const files = fs.readdirSync(nodesDir);
        const recentNodes = files
            .filter(file => {
                return file.endsWith('.json') && 
                       !['root.json', 'bulletin.json', 'filters.json', 'phantom_nodes.json'].includes(file);
            }) 
            .map(file => {
                try {
                    const data = JSON.parse(fs.readFileSync(path.join(nodesDir, file), 'utf8'));
                    const stats = fs.statSync(path.join(nodesDir, file));
                    const currentId = file.replace('.json', '');
                    
                    return { 
                        id: currentId, 
                        title: data.title || "Untitled Fragment", 
                        mtime: stats.mtime,
                        author: data.author || 'User',
                        isStatic: data.isStatic || false,
                        // Fix URL based on static status
                        url: data.isStatic ? `/sites/${currentId}.html` : `/node/${currentId}`
                    };
                } catch (e) { return null; }
            })
            .filter(node => node !== null)
            .sort((a, b) => b.mtime - a.mtime)
            .slice(0, 5);

        // 7. BULLETIN DATA
        let bulletin = [];
        const finalBulletinPath = fs.existsSync(path.join(nodesDir, 'bulletin.json')) 
            ? path.join(nodesDir, 'bulletin.json') 
            : path.join(__dirname, 'bulletin.json');

        if (fs.existsSync(finalBulletinPath)) {
            try { bulletin = JSON.parse(fs.readFileSync(finalBulletinPath, 'utf8')); } catch (e) {}
        }

        // 8. DYNAMIC CAPTCHA
        const num1 = Math.floor(Math.random() * 10) + 1;
        const num2 = Math.floor(Math.random() * 10) + 1;
        req.session.captchaAnswer = num1 + num2;
        const captchaQuestion = `${num1} + ${num2}`;

        // 9. RENDER
        res.render('node-template', { 
            node,
            captchaQuestion,
            recentNodes, 
            bulletin, 
            broadcast, 
            maintenanceMode: maintenanceStatus 
        });

    } catch (err) {
        console.error("CRITICAL NODE RENDER ERROR:", err);
        res.status(500).send("<h1>SECTOR CORRUPTION</h1><p>The data fragment is unreadable.</p>");
    }
});

// 1. Show the page
app.get('/login', (req, res) => {
    res.render('login', { error: null }); 
});

app.post('/login', (req, res) => {
    const { username, password } = req.body;

    if (username === process.env.ADMIN_USER && password === process.env.ADMIN_PASS) {
        req.session.authenticated = true;
        req.session.adminPassword = password; // Store it for your buttons
        res.redirect('/admin-portal'); // Look! No more ?key= in the URL!
    } else {
        res.render('login', { error: "INVALID CREDENTIALS" });
    }
});




app.post('/spawn/:parentId', spawnLimiter, (req, res) => {
    try {
        const { title, htmlContent, captchaInput } = req.body;
        
        // 1. Humanity Check
        if (parseInt(captchaInput) !== req.session.captchaAnswer) {
            return res.status(403).send("Captcha failed.");
        }

        // 2. Generate the ID & Sanitize
        const nodeId = uuidv4().substring(0, 8);
        const safeHtml = sanitizeContent(htmlContent); 

        // 3. THE BAKE (Updated for high-compatibility)
        const fullHtmlPage = `
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <link rel="icon" type="image/x-icon" href="/favicon.ico?v=1">
            <title>${title}</title>
            <link rel="stylesheet" href="/style.css">
        </head>
        <body style="background-color: #008080; margin: 0; padding: 10px;">
            <div class="window-full">
                <div class="title-bar">
                    <span>Sector: ${title}</span>
                    <span>X</span>
                </div>
                <div class="content-area">
                    <div class="main-content">
                        ${safeHtml}
                    </div>
                    
                    <hr style="margin-top: 50px;">
                    <center>
                        <button onclick="window.location.href='/node/root'">[ Return to Node Net ]</button>
                        <a href="${nodeId}.html" download="${title}.html" style="margin-left: 10px;">[ Download Source ]</a>
                    </center>
                </div>
            </div>
        </body>
        </html>`;

        // 4. SAVE THE PHYSICAL HTML FILE
        const filePath = path.join(__dirname, 'public_sites', `${nodeId}.html`);
        fs.writeFileSync(filePath, fullHtmlPage);

        // 4.5 CREATE THE NODE METADATA
        const newNodeData = {
            id: nodeId,
            title: title,
            isStatic: true,
            views: 0,
            children: [],
            parentId: req.params.parentId,
            timestamp: new Date().toISOString()
        };
        const nodePath = path.join(__dirname, 'nodes', `${nodeId}.json`);
        fs.writeFileSync(nodePath, JSON.stringify(newNodeData, null, 2));

        // 5. UPDATE THE PARENT'S TREE
        const parentPath = path.join(__dirname, 'nodes', `${req.params.parentId}.json`);
        if (fs.existsSync(parentPath)) {
            const parentData = JSON.parse(fs.readFileSync(parentPath, 'utf8'));
            parentData.children.push({ id: nodeId, title: title, isStatic: true });
            fs.writeFileSync(parentPath, JSON.stringify(parentData, null, 2));
        }

        // --- SECTION 5.5: AUTOMATED GRAFFITI ANNOUNCEMENT (FIXED TO ROOT) ---
        const bulletinPath = path.join(__dirname, 'bulletin.json'); 
        let bulletin = [];

        // Read current board
        if (fs.existsSync(bulletinPath)) {
            try {
                bulletin = JSON.parse(fs.readFileSync(bulletinPath, 'utf8'));
            } catch (e) { 
                console.error("Bulletin read error during spawn:", e);
                bulletin = []; 
            }
        }

        const systemMessage = {
            username: "SYSTEM_BOT",
            message: `🚀 NEW SECTOR BAKED: "${title}" is now online! Check it out at /sites/${nodeId}.html`,
            date: new Date().toLocaleString()
        };

        // Add to the START of the array
        bulletin.unshift(systemMessage); 
        
        // Keep only the most recent 50 messages
        if (bulletin.length > 50) {
            bulletin = bulletin.slice(0, 50);
        }
        
        // Write back to root
        fs.writeFileSync(bulletinPath, JSON.stringify(bulletin, null, 2));
        // ----------------------------------------------------

        // 6. REDIRECT
        res.redirect(`/sites/${nodeId}.html`);

    } catch (error) {
        console.error("Bake Error:", error);
        res.status(500).send("The Architect encountered a baking error.");
    }
});

app.post('/bulletin/post', (req, res) => {
    // 1. Check for Lockdown
    if (typeof maintenanceMode !== 'undefined' && maintenanceMode) {
        return res.status(503).send("SYSTEM LOCKDOWN: The board is temporarily closed for maintenance.");
    }

    const { username, message } = req.body;
    const boardPath = path.join(__dirname, 'bulletin.json'); 
    const filterPath = path.join(__dirname, 'nodes', 'filters.json');

    // 2. Load the Banned Words list
    let bannedWords = [];
    try {
        if (fs.existsSync(filterPath)) {
            const filterData = JSON.parse(fs.readFileSync(filterPath, 'utf8'));
            bannedWords = filterData.bannedWords || [];
        }
    } catch (e) {
        console.error("::: FILTER READ ERROR :::", e);
        // If file fails, we proceed with an empty list rather than crashing
    }

    // 3. Perform the Security Scan
    // We check the username AND message for any banned phrases
    const contentToCheck = `${username} ${message}`.toLowerCase();
    const foundBadWord = bannedWords.find(word => 
        word.trim() !== "" && contentToCheck.includes(word.toLowerCase().trim())
    );

    if (foundBadWord) {
        return res.status(400).send(`
            <script>
                alert("ACCESS DENIED: Your post contains the forbidden term '${foundBadWord}'. Please keep the network clean.");
                window.location.href = "/node/root";
            </script>
        `);
    }

    // 4. Sanitize and Prep the Data
    // We escape < and > to prevent people from putting 
    // nasty scripts or broken HTML into your board.
    const safeUsername = (username || "Anon").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    const safeMessage = (message || "").replace(/</g, "&lt;").replace(/>/g, "&gt;");

    if (!safeMessage.trim()) {
        return res.redirect('/node/root'); // Don't post empty messages
    }

    // 5. Read, Update, and Save the Board
    let posts = [];
    try {
        if (fs.existsSync(boardPath)) {
            posts = JSON.parse(fs.readFileSync(boardPath, 'utf8'));
        }
    } catch (e) {
        posts = [];
    }

    // Add new post to the top
    posts.unshift({ 
        username: safeUsername, 
        message: safeMessage, 
        date: new Date().toLocaleString() 
    });

    // Keep only the most recent 15 posts to save disk space
    fs.writeFileSync(boardPath, JSON.stringify(posts.slice(0, 15), null, 2));

    console.log(`::: NEW BULLETIN FROM ${safeUsername} :::`);
    
    // Redirect back to the homepage/root
    res.redirect('/node/root'); 
});


app.post('/admin/panic', (req, res) => {
    const { adminPass } = req.body;
    if (adminPass !== process.env.ADMIN_PASS) return res.status(403).send("Unauthorized");

    // 1. Toggle the lock
    maintenanceMode = !maintenanceMode;

    // 2. Run an immediate cleanup if locking down
    if (maintenanceMode) {
        runGarbageCollector();
        console.log("[PANIC]: System entered lockdown. Cleanup triggered.");
    } else {
        console.log("[PANIC]: System released from lockdown.");
    }

    res.redirect(`/admin-portal?key=${adminPass}`);
});

app.get('/search', (req, res) => {
    try {
        const query = req.query.q ? req.query.q.toLowerCase() : '';
        
        // 1. Get files and filter for ONLY .json files
        const files = fs.readdirSync('./nodes').filter(f => f.endsWith('.json'));
        
        const results = files.map(f => {
            try {
                return JSON.parse(fs.readFileSync(`./nodes/${f}`, 'utf8'));
            } catch (e) {
                return null; // Skip files that are corrupted
            }
        })
        .filter(d => d && d.title && d.title.toLowerCase().includes(query));

        // 2. Render (Make sure views/search-results.ejs exists!)
        res.render('search-results', { results, query });
        
    } catch (error) {
        console.error("Search failed:", error);
        res.status(500).send("Search Engine Failure - Internal Error");
    }
});

app.get('/random', (req, res) => {
    const sitesDir = path.join(__dirname, 'sites');

    if (!fs.existsSync(sitesDir)) {
        return res.redirect('/node/root');
    }

    const bakedFiles = fs.readdirSync(sitesDir).filter(f => f.endsWith('.html'));

    if (bakedFiles.length === 0) {
        return res.redirect('/node/root');
    }

    // Pick the random filename (e.g., "cb07f03e.html")
    const randomSite = bakedFiles[Math.floor(Math.random() * bakedFiles.length)];

    // REDIRECT FIX: 
    // Use /sites/ (the public URL) and don't add .html again
    res.redirect(`/sites/${randomSite}`);
});

// --- ADMIN ROUTES ---


const isAdmin = (req, res, next) => {
    if (req.session && req.session.authenticated) return next();
    res.redirect('/login');
};


app.get('/admin-portal', isAdmin, (req, res) => {
    // Retrieve the admin password from the session
    const key = req.session.adminPassword; 

    try {
        // 1. GATHER NODE DATA
        if (!fs.existsSync('./nodes')) fs.mkdirSync('./nodes');
        if (!fs.existsSync('./cemetery')) fs.mkdirSync('./cemetery');

        const nodeFiles = fs.readdirSync('./nodes').filter(f => f.endsWith('.json'));
        const deadFiles = fs.readdirSync('./cemetery').filter(f => f.endsWith('.json'));

        // 2. GATHER BULLETIN DATA
        let bulletinData = [];
        const bulletinPath = './nodes/bulletin.json'; 
        const oldPath = './bulletin.json';
        const finalPath = fs.existsSync(bulletinPath) ? bulletinPath : oldPath;

        if (fs.existsSync(finalPath)) {
            try {
                bulletinData = JSON.parse(fs.readFileSync(finalPath, 'utf8'));
            } catch (err) {
                console.error("Malformed bulletin.json file:", err);
                bulletinData = [];
            }
        }

        // 3. CALCULATE SYSTEM WEIGHT
        const getDirSize = (dir, files) => {
            return files.reduce((acc, file) => {
                try {
                    const stats = fs.statSync(path.join(dir, file));
                    return acc + stats.size;
                } catch (e) {
                    return acc; 
                }
            }, 0);
        };

        const nodesWeightKB = (getDirSize('./nodes', nodeFiles) / 1024);
        const cemeteryWeightKB = (getDirSize('./cemetery', deadFiles) / 1024);
        const totalWeight = (nodesWeightKB + cemeteryWeightKB).toFixed(2);

        const ratio = (totalWeight > 0) 
            ? ((cemeteryWeightKB / totalWeight) * 100).toFixed(1) 
            : 0;

        // 4. RENDER THE DASHBOARD
        res.render('admin-dash', {
            // --- UPDATED ALLNODES MAPPING ---
            allNodes: nodeFiles.map(f => {
                try {
                    const data = JSON.parse(fs.readFileSync(`./nodes/${f}`, 'utf8'));
                    return { 
                        ...data, 
                        slug: f.replace('.json', ''),
                        // Explicitly ensuring author is passed, default to 'Unknown'
                        author: data.author || 'User' 
                    };
                } catch (e) {
                    return { id: f, title: "CORRUPT NODE", author: "SYSTEM" };
                }
            }),
            // --- END OF UPDATED SECTION ---

            deadNodes: deadFiles.map(f => {
                const data = JSON.parse(fs.readFileSync(`./cemetery/${f}`, 'utf8'));
                return { ...data, slug: f.replace('.json', '') };
            }),
            bulletin: bulletinData, 
            
            gcLogs: fs.existsSync('./gc_history.log') 
                ? fs.readFileSync('./gc_history.log', 'utf8').trim().split('\n').slice(-5).reverse() 
                : ["No logs found. System healthy."],
            
            stats: {
                liveCount: nodeFiles.length,
                deadCount: deadFiles.length,
                totalWeight: totalWeight,
                ratio: ratio
            },
            
            maintenanceMode: typeof maintenanceMode !== 'undefined' ? maintenanceMode : false,
            key: key 
        });

    } catch (error) {
        console.error("CRITICAL ADMIN PORTAL ERROR:", error);
        res.status(500).send("Admin Portal failed to load. Check server logs.");
    }
});

app.get('/admin/audit-network', isAdmin, (req, res) => {
    const filterPath = './nodes/filters.json';
    const nodesDir = './nodes';

    try {
        // 1. Load Banned Words
        let bannedWords = [];
        if (fs.existsSync(filterPath)) {
            bannedWords = JSON.parse(fs.readFileSync(filterPath, 'utf8')).bannedWords || [];
        }

        // 2. Scan all JSON files in /nodes
        const files = fs.readdirSync(nodesDir).filter(f => f.endsWith('.json') && f !== 'filters.json' && f !== 'bulletin.json');
        
        const flaggedSites = [];

        files.forEach(file => {
            const data = JSON.parse(fs.readFileSync(path.join(nodesDir, file), 'utf8'));
            const contentToScan = `${data.title} ${data.content}`.toLowerCase();
            
            // Check if any banned word exists in this specific site
            const violations = bannedWords.filter(word => contentToScan.includes(word.toLowerCase().trim()));

            if (violations.length > 0) {
                flaggedSites.push({
                    id: data.id,
                    title: data.title,
                    violations: violations
                });
            }
        });

        // 3. Render a special audit page (or send data back to dash)
        res.render('admin-audit', { 
            flaggedSites, 
            key: req.session.adminPassword 
        });

    } catch (e) {
        console.error("Audit failed:", e);
        res.status(500).send("Audit Error");
    }
});


app.post('/edit/:id', (req, res) => {
    const { title, content, adminPass } = req.body;
    if (adminPass !== process.env.ADMIN_PASS) return res.status(403).send("Unauthorized");

    const filePath = `./nodes/${req.params.id}.json`;
    if (fs.existsSync(filePath)) {
        const node = JSON.parse(fs.readFileSync(filePath));
        node.title = title;
        node.content = sanitizeContent(content); // SAFETY NET APPLIED
        fs.writeFileSync(filePath, JSON.stringify(node));
        res.redirect(`/node/${req.params.id}`);
    }
});

app.post('/admin/broadcast', (req, res) => {
    const { message, adminPass, clearBroadcast } = req.body;
    
    if (adminPass !== process.env.ADMIN_PASS) {
        return res.status(403).send("Unauthorized");
    }

    const broadcastPath = './broadcast.json';

    if (clearBroadcast === "true" || !message || message.trim() === "") {
        fs.writeFileSync(broadcastPath, JSON.stringify(null));
        app.locals.broadcast = null;
        console.log("::: BROADCAST SIGNAL TERMINATED :::");
    } else {
        const broadcastData = { message: message.trim() };
        fs.writeFileSync(broadcastPath, JSON.stringify(broadcastData));
        app.locals.broadcast = broadcastData;
        console.log("::: NEW BROADCAST TRANSMITTED :::");
    }

    // CHANGE: Redirect specifically to your admin route
    res.redirect('/admin-portal'); 
});

app.post('/admin/clear-bulletin', (req, res) => {
    if (req.body.adminPass !== process.env.ADMIN_PASS) {
        return res.status(403).send("Unauthorized");
    }
    
    fs.writeFileSync('./bulletin.json', JSON.stringify([]));
    
    // CHANGE: Redirect specifically to your admin route
    res.redirect('/admin-portal');
});


app.post('/admin/delete-bulletin/:index', (req, res) => {
    // 1. Check admin pass (ensure it's coming from req.body)
    if (req.body.adminPass !== process.env.ADMIN_PASS) {
        return res.status(403).send("Unauthorized");
    }

    try {
        const bulletinPath = './bulletin.json';
        
        // 2. Read and parse with a fallback to an empty array
        let bulletin = [];
        if (fs.existsSync(bulletinPath)) {
            bulletin = JSON.parse(fs.readFileSync(bulletinPath, 'utf8'));
        }

        // 3. Get the index from the URL
        const indexToDelete = parseInt(req.params.index);

        // 4. Validation: Check if index is a valid number and within array bounds
        if (!isNaN(indexToDelete) && indexToDelete >= 0 && indexToDelete < bulletin.length) {
            
            // IMPORTANT: If your admin UI displays the list REVERSED, 
            // you must delete from the original array correctly.
            // If the UI is NOT reversed, simple splice works:
            bulletin.splice(indexToDelete, 1);
            
            fs.writeFileSync(bulletinPath, JSON.stringify(bulletin, null, 2));
            console.log(`::: ADMIN: Successfully removed post #${indexToDelete} :::`);
        } else {
            console.log(`::: ADMIN: Delete failed. Invalid index: ${indexToDelete} :::`);
        }

        // 5. Explicit redirect back to the dashboard
        res.redirect('/admin-portal');

    } catch (e) {
        console.error("CRITICAL ERROR in delete-bulletin:", e);
        res.status(500).send("Internal Server Error: Check console logs.");
    }
});

app.post('/admin/toggle-construction/:id', (req, res) => {
    if (req.body.adminPass !== process.env.ADMIN_PASS) return res.status(403).send("Unauthorized");
    const filePath = `./nodes/${req.params.id}.json`;
    const node = JSON.parse(fs.readFileSync(filePath));
    node.isUnderConstruction = !node.isUnderConstruction;
    fs.writeFileSync(filePath, JSON.stringify(node));
    res.redirect('back');
});

app.post('/delete/:id', (req, res) => {
    const { adminPass, reason } = req.body;
    const targetId = req.params.id;

    if (adminPass !== process.env.ADMIN_PASS) return res.status(403).send("Unauthorized");
    
    const node = JSON.parse(fs.readFileSync(`./nodes/${targetId}.json`));
    
    // Use the shared tools!
    healNode(node.id, node.parentId, node.children || []);
    archiveDeletion(node, reason || "Manual Admin Delete");
    
    fs.unlinkSync(`./nodes/${targetId}.json`);
    res.redirect(`/admin-portal?key=${adminPass}`);
});

// --- ADMIN: EXPORT ENTIRE NETWORK ---
app.get('/admin/export', (req, res) => {
    const { key } = req.query;
    if (key !== process.env.ADMIN_PASS) return res.status(403).send("Unauthorized");

    res.attachment(`eurosnet_full_backup_${Date.now()}.zip`);
    const archive = archiver('zip', { zlib: { level: 9 } });

    archive.on('error', (err) => res.status(500).send({ error: err.message }));
    archive.pipe(res);

    // --- DIRECTORIES ---
    // Added 'sites' to ensure Phantoms are backed up
    const dirsToBackup = [
        { real: 'nodes/', alias: 'nodes' },
        { real: 'sites/', alias: 'sites' }, // The static baked Phantoms
        { real: 'public/', alias: 'public' }, 
        { real: 'views/', alias: 'views' }
    ];

    dirsToBackup.forEach(dir => {
        const fullPath = path.join(__dirname, dir.real);
        if (fs.existsSync(fullPath)) {
            archive.directory(fullPath, dir.alias);
        }
    });

    // --- SYSTEM FILES ---
    const filesToInclude = ['bulletin.json', 'broadcast.json', 'phantom_nodes.json', 'server.js', 'page_bot.js'];
    filesToInclude.forEach(file => {
        const fullPath = path.join(__dirname, file);
        if (fs.existsSync(fullPath)) {
            archive.file(fullPath, { name: file });
        }
    });

    archive.finalize();
});

// --- ADMIN: RESTORE NETWORK FROM ZIP ---
app.post('/admin/restore', upload.single('backupZip'), async (req, res) => {
    const { adminPass } = req.body;
    if (adminPass !== process.env.ADMIN_PASS) return res.status(403).send("Unauthorized");
    if (!req.file) return res.status(400).send("No file uploaded.");

    const zipPath = req.file.path;

    try {
        // 1. CLEAR EXISTING DIRECTORIES
        // Added './sites' to the wipe list
        const foldersToClear = ['./nodes', './sites', './views', './public'];
        
        foldersToClear.forEach(dir => {
            const fullPath = path.resolve(__dirname, dir);
            if (fs.existsSync(fullPath)) {
                fs.rmSync(fullPath, { recursive: true, force: true });
                fs.mkdirSync(fullPath); 
            }
        });

        // 2. EXTRACT ZIP
        // Extraction to root ensures 'nodes/' and 'sites/' land in the right spot
        await fs.createReadStream(zipPath)
            .pipe(unzipper.Extract({ path: path.join(__dirname, './') }))
            .promise();

        fs.unlinkSync(zipPath); // Delete the uploaded temp zip

        res.send("<h2>Full System Restored.</h2><p>Sectors, Nodes, and Phantoms updated.</p><a href='/admin-portal'>Return to Admin</a>");
        
        // Restart to apply system file changes (server.js / page_bot.js)
        setTimeout(() => process.exit(0), 1500); 
    } catch (err) {
        console.error("Restore Error:", err);
        res.status(500).send("Restore failed: " + err.message);
    }
});


app.post('/admin/run-gc', (req, res) => {
    const { adminPass } = req.body;
    if (adminPass !== process.env.ADMIN_PASS) return res.status(403).send("Unauthorized");
    
    const count = runGarbageCollector();
    res.send(`<h2>Janitor complete. ${count} nodes were scrapped.</h2><a href="/admin-portal?key=${adminPass}">Back</a>`);
});

app.post('/admin/revive/:id', (req, res) => {
    const { adminPass } = req.body;
    if (adminPass !== process.env.ADMIN_PASS) return res.status(403).send("Unauthorized");

    const result = reviveNode(req.params.id);
    
    if (result.success) {
        res.redirect(`/admin-portal?key=${adminPass}`);
    } else {
        res.status(400).send(result.message);
    }
});

app.post('/admin/trigger-architect', (req, res) => {
    const { adminPass } = req.body;
    if (adminPass !== process.env.ADMIN_PASS) return res.status(403).send("Unauthorized");

    // We call the function from our page_bot.js
    if (typeof generatePhantomNode === "function") {
        generatePhantomNode();
        res.redirect(`/admin-portal?key=${adminPass}&msg=Architect_Triggered`);
    } else {
        res.status(500).send("Architect Bot not loaded in current sector.");
    }
});

app.get('/api/phantoms', (req, res) => {
    const nodesDir = path.join(__dirname, 'nodes');
    const files = fs.readdirSync(nodesDir);
    
    const phantoms = files
        .filter(f => f.endsWith('.json'))
        .map(f => {
            try {
                return JSON.parse(fs.readFileSync(path.join(nodesDir, f), 'utf8'));
            } catch (e) { return null; }
        })
        .filter(n => n && n.author === "THE_ARCHITECT");

    res.json(phantoms);
});





app.listen(port, () => {
    console.log(`[SYSTEM ONLINE]: Architect Terminal active on port ${port}`);
    
    // --- START THE JANITOR ---
    // This starts the timer as soon as the server is live.
    // 1000ms * 60s * 60m = 1 Hour
    setInterval(runGarbageCollector, 1000 * 60 * 60);
    // Run the bot every 4 hours
    setInterval(spawnNewsSector, 1000 * 60 * 60 * 4);

    // 1. RUN IMMEDIATELY ON STARTUP
    try {
        console.log("[!] ARCHITECT: Initializing immediate materialization...");
        generatePhantomNode(); 
    } catch (err) {
        console.error("[!] ARCHITECT STARTUP ERROR:", err);
    }

    // 2. SET THE RECURRING SCHEDULE (Every 4 Hours)
    setInterval(() => {
        try {
            generatePhantomNode();
        } catch (err) {
            console.error("[!] ARCHITECT INTERVAL ERROR:", err);
        }
    }, 1000 * 60 * 60 * 4);

    console.log("[BOT]: Architect scheduled for 4-hour intervals."); 

    console.log("[GC]: Garbage Collector scheduled for 1-hour intervals.");
});